spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skill_app
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      hbm2ddl:
        auto: none
server:
  port: 8080
